adding ParseMax w/ max form size in signature - forwarded to from Parse
albrow/forms pull request #4
Opened 2017-01-10 14:59 UTC by dadleyy

closes #3

2017-01-10 15:29 UTC, albrow requested changes
I just left one small comment. After it's addressed and I've confirmed the tests pass, I'll merge.

2017-01-10 15:29 UTC, albrow commented on data.go
> +const DefaultMaxFormSize = 2048
I like for all exported identifiers to have doc comments. Mind adding a comment here? It doesn't have to be long. Just something like:

```
// DefaultMaxFormSize is the default maximum form size (in bytes) used by the Parse function.
```

Also, I know this is my fault, but I think 2048 is probably much too small. I want to find a value that is likely to be safe (i.e. is unlikely to cause OOM exceptions in most environments) and allows for common things like text files, pdfs, and smaller images. Shall we try something around 500 KB?

2017-01-10 15:31 UTC, dadleyy commented on data.go
> +const DefaultMaxFormSize = 2048
Sounds good to me. I'll update in a bit! Thanks

2017-01-10 16:51 UTC, dadleyy commented
@albrow just made your changes. I also added a [`.travis.yaml`](https://github.com/dadleyy/forms/blob/master/.travis.yml) file. It [runs the tests](https://travis-ci.org/dadleyy/forms).

2017-02-01 00:01 UTC, albrow commented
@dadleyy thanks for updating this PR. I'm sorry for the delay, but my main development computer has been out of commission for a while. I'll likely be up and running again in the next week or so and I can do a more thorough review at that time.

> I also added a .travis.yaml file.

Thank you for this :) I have nothing against Travis but I've been using CircleCI for many of my other projects  ([albrow/zoom](https://github.com/albrow/zoom) for example) and I'm more familiar with it. I'll leave __.travis.yaml__ there for now but I'll likely remove it after I set up CircleCI.

2017-02-15 23:13 UTC, albrow approved these changes

2017-02-15 23:13 UTC, merged

2017-02-15 23:15 UTC, albrow commented
Thanks again, @dadleyy! I merged this and released version 0.4.0.